import "../globals.css";
import SearchHeader from "../components/SearchHeader";


export const metadata = {
  title: "Google in jsx",
  description: "Generated by create next app",
};

export default function SearchLayout({ children }) {
  return (
    <div lang="en">
        <SearchHeader />
      
        {children}
        
        
        
    </div>
  );
}
